# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Business' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Business

  target 'BusinessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BusinessUITests' do
    # Pods for testing
  end
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'

end
